import { AppDataSource } from './data-source';

export interface MigrationsResult {
  applied: number;
}

// Migrations anteriores ao synchronize (aplicadas pelo auto-heal do schema).
// Se não estiverem registradas na tabela de migrations, tentamos executá-las;
// se falharem porque o schema já existe, marcamos como executadas (baseline).
const BASELINE_MIGRATION_NAMES = new Set([
  'CreateAuditLogs1787000000000',
  'AddReceptionAssignments1787000001000',
  'AddBoothRuleSets1787000002000',
  'AddBoothLifecycle1787000003000',
  'GeneralizeOnboardingLinks1787000004000',
  'ConfigurePresenceConfirmationWindow1787000005000',
  'AddBrokerManagementState1787000006000',
  'CleanupAbiatarTestUsers1787000007000',
  'AddPasswordResetState1787000008000',
  'ResetAbiatarTestForRecreation1787000009000',
  'AddTenantWhiteLabelSettings1787000010000',
  'AddPresenceConfirmationCycle1787000011000',
  'AddBoothRulePeriods1787000012000',
  'AddBrokerStageColumn1787000013000',
]);

type MigrationInstance = {
  name?: unknown;
  transaction?: unknown;
  up?: (runner: unknown) => Promise<void>;
  down?: (runner: unknown) => Promise<void>;
};

function migrationName(migration: MigrationInstance): string {
  const explicit = typeof migration.name === 'string' && migration.name ? migration.name : undefined;
  if (explicit) return explicit;
  const ctor = migration.constructor as { name?: string } | undefined;
  return ctor?.name ?? 'MigrationSemNome';
}

export async function runPendingMigrations(): Promise<MigrationsResult> {
  if (!AppDataSource.isInitialized) {
    await AppDataSource.initialize();
  }
  const queryRunner = AppDataSource.createQueryRunner();
  try {
    await queryRunner.connect();

    await queryRunner.query(`
      CREATE TABLE IF NOT EXISTS migrations (
        "id" integer GENERATED BY DEFAULT AS IDENTITY NOT NULL,
        "timestamp" bigint NOT NULL,
        name character varying NOT NULL,
        CONSTRAINT "PK_migrations" PRIMARY KEY ("id")
      )
    `);

    const rawExecuted: Array<{ name: string }> = await queryRunner.query('SELECT name FROM migrations');
    const executedNames = new Set(rawExecuted.map((row) => row.name));
    const registered = AppDataSource.migrations as unknown as MigrationInstance[];
    let applied = 0;

    for (const migration of registered) {
      const name = migrationName(migration);
      if (executedNames.has(name)) continue;

      const isCritical = !BASELINE_MIGRATION_NAMES.has(name);
      try {
        if (typeof migration.up !== 'function') {
          throw new Error('instância da migration não possui método up');
        }

        if (migration.transaction === false) {
          await migration.up(queryRunner);
        } else {
          await queryRunner.startTransaction();
          try {
            await migration.up(queryRunner);
            await queryRunner.commitTransaction();
          } catch (error) {
            await queryRunner.rollbackTransaction();
            throw error;
          }
        }

        await queryRunner.query('INSERT INTO migrations ("timestamp", name) VALUES ($1, $2)', [
          Date.now(),
          name,
        ]);
        applied++;
        console.log(`[MIGRATIONS] ${name} aplicada com sucesso.`);
      } catch (error) {
        const message = error instanceof Error ? error.message : String(error);
        if (isCritical) {
          console.error(`[MIGRATIONS] CRÍTICO: ${name} FALHOU: ${message}`);
          throw error;
        }
        console.warn(
          `[MIGRATIONS] ${name} já estava aplicada pelo synchronize (baseline); registrando como executada. ${message}`,
        );
        await queryRunner.query('INSERT INTO migrations ("timestamp", name) VALUES ($1, $2)', [
          Date.now(),
          name,
        ]);
      }
    }

    console.log(`[MIGRATIONS] ${applied} migration(s) nova(s) aplicada(s).`);
    return { applied };
  } finally {
    if (!queryRunner.isReleased) {
      await queryRunner.release();
    }
    if (AppDataSource.isInitialized) {
      await AppDataSource.destroy();
    }
  }
}

// Execução direta quando chamado como script: npx ts-node src/database/run-migrations.ts
if (require.main === module) {
  void runPendingMigrations().catch((error) => {
    console.error('[MIGRATIONS] Falha ao executar migrations:', error);
  });
}